version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Runs only on first startup, creates the alerts table
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    environment:
      PORT: 3000
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGHOST: postgres
      PGPORT: 5432
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      AUTH_API_URL: ${AUTH_API_URL}
      LEAD_API: ${LEAD_API}
      ACCOUNT_API: ${ACCOUNT_API}
      AUTHORIZATION: ${AUTHORIZATION}
      USER_AGENT: ${USER_AGENT}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    environment:
      BACKEND_URL: /
    ports:
      - "80:80"

volumes:
  pg_data: