version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    env_file:
      - .env.db
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    env_file:
      - .env.backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    ports:
      - "80:80"

volumes:
  pg_data: